#!/bin/bash

sudo systemctl stop clamav-freshclam.service
sudo systemctl disable clamav-freshclam.service
sudo systemctl unmask clamav-freshclam.service
sudo systemctl stop clamav-daemon.service
sudo systemctl disable clamav-daemon.service
sudo systemctl unmask clamav-daemon.service
sudo systemctl stop clamav-clamonacc.service
sudo systemctl disable clamav-clamonacc.service
sudo systemctl unmask clamav-clamonacc.service
sudo rm -R /var/log/clamav
sudo rm -R /var/lib/clamav
sudo rm /etc/sysctl.d/60-clamav.conf
sudo rpm -e clamav
